<?php
/** Full Content Template
 *
 * Template Name:  Full Width Page (Gutenberg)
 *
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

get_header();

do_action( 'ifeature_cc_before_container' );

do_action( 'ifeature_cc_page_content' );

do_action( 'ifeature_cc_after_container' );

get_footer();
